# Generated by Django 3.2.8 on 2022-01-17 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20220109_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addresses',
            options={'ordering': ('state', 'city', 'address_1'), 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.RenameField(
            model_name='addresses',
            old_name='address1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='addresses',
            old_name='address2',
            new_name='address_2',
        ),
    ]
