# Generated by Django 3.2.8 on 2022-01-17 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_model', models.CharField(choices=[('User', 'User'), ('Companies', 'Companies'), ('CompanyInviteList', 'Company Invite List'), ('Addresses', 'Addresses'), ('Contacts', 'Contacts'), ('Documents', 'Documents'), ('Images', 'Images'), ('GeneralLedgerCodes', 'General Ledger Codes'), ('Notes', 'Notes'), ('---', 'Invalid')], default='---', max_length=127, verbose_name='Model Name')),
                ('model_id', models.BigIntegerField(verbose_name='Reference Model ID Value')),
                ('field_name', models.CharField(max_length=127, verbose_name='Model Field Name')),
                ('previous_value', models.TextField(verbose_name='Previously Stored Value')),
                ('previous_value_type', models.CharField(max_length=7, verbose_name='Field Type __name__')),
                ('changed_on', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
