# Generated by Django 3.2.8 on 2022-01-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('change_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'ordering': ('-changed_on',), 'verbose_name': 'Change Log', 'verbose_name_plural': 'Changes Log'},
        ),
        migrations.RenameField(
            model_name='changelog',
            old_name='changed_by',
            new_name='previous_user',
        ),
    ]
