# Generated by Django 3.2.8 on 2021-12-06 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0002_auto_20211130_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='company_user_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companies',
            name='allowed_viewers',
            field=models.ManyToManyField(blank=True, related_name='company_viewers_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CompanyInviteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Invited user')),
                ('admin_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_admin_company_set', to='companies.companies')),
                ('viewer_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invite_viewer_company_set', to='companies.companies')),
            ],
        ),
        migrations.AddConstraint(
            model_name='companyinvitelist',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('admin_in__isnull', True), ('viewer_in__isnull', False)), models.Q(('admin_in__isnull', False), ('viewer_in__isnull', True)), _connector='OR'), name='companies_companyinvitelist_admin_in_or_viewer_in'),
        ),
    ]
