# Generated by Django 3.2.8 on 2021-12-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20211212_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='accounts_payable',
            field=models.BooleanField(default=False, verbose_name='Accounts Payable Extension'),
        ),
        migrations.AddField(
            model_name='companies',
            name='accounts_receivable',
            field=models.BooleanField(default=False, verbose_name='Accounts Receivable Extension'),
        ),
        migrations.AddField(
            model_name='companies',
            name='maintenance',
            field=models.BooleanField(default=False, verbose_name='Maintenance Extension'),
        ),
    ]
