# Generated by Django 3.2.8 on 2021-12-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_auto_20211218_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='accounts_payable',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='accounts_receivable',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='maintenance',
        ),
        migrations.AddField(
            model_name='companies',
            name='accounts_payable_extension',
            field=models.BooleanField(default=False, verbose_name='Accounts Payable Package Extension'),
        ),
        migrations.AddField(
            model_name='companies',
            name='accounts_receivable_extension',
            field=models.BooleanField(default=False, verbose_name='Accounts Receivable Package Extension'),
        ),
        migrations.AddField(
            model_name='companies',
            name='maintenance_extension',
            field=models.BooleanField(default=False, verbose_name='Maintenance Package Extension'),
        ),
    ]
