# Generated by Django 3.2.8 on 2021-12-20 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20211218_2026'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyinvitelist',
            unique_together={('email', 'admin_in', 'viewer_in')},
        ),
    ]
