# Generated by Django 3.2.8 on 2021-12-20 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_alter_companyinvitelist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinvitelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyinvitelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
