# Generated by Django 3.2.8 on 2022-01-02 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_auto_20211219_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinvitelist',
            options={'ordering': ('-updated_at', 'email'), 'verbose_name': 'Company Invite List', 'verbose_name_plural': 'Company Invites List'},
        ),
    ]
