# Generated by Django 3.2.8 on 2022-01-09 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_ledger', '0003_auto_20211218_2011'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0002_auto_20211218_2328'),
        ('documents', '0003_auto_20220102_1649'),
        ('notes', '0003_alter_notes_user'),
        ('companies', '0012_auto_20220102_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(blank=True, max_length=255)),
                ('build_year', models.DateField(blank=True, null=True)),
                ('allowed_admins', models.ManyToManyField(blank=True, related_name='building_user_set', to=settings.AUTH_USER_MODEL)),
                ('allowed_viewers', models.ManyToManyField(blank=True, related_name='building_viewers_set', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings_company_set', to='companies.companies')),
                ('documents', models.ManyToManyField(blank=True, related_name='building_documents_set', to='documents.Documents')),
                ('gl_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_gl_codes_set', to='general_ledger.generalledgercodes')),
                ('images', models.ManyToManyField(blank=True, related_name='building_images_set', to='documents.Images')),
                ('notes', models.ManyToManyField(blank=True, related_name='building_notes_set', to='notes.Notes')),
                ('physical_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='building_physical_address_set', to='contacts.addresses')),
            ],
            options={
                'verbose_name': 'Building',
                'verbose_name_plural': 'Buildings',
                'ordering': ('company', 'building_name'),
            },
        ),
    ]
