# Generated by Django 3.2.8 on 2022-01-09 17:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20220109_1019'),
        ('companies', '0012_auto_20220102_1606'),
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildings',
            options={'ordering': ('company', 'name'), 'verbose_name': 'Building', 'verbose_name_plural': 'Buildings'},
        ),
        migrations.RenameField(
            model_name='buildings',
            old_name='building_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='buildings',
            name='physical_address',
        ),
        migrations.AddField(
            model_name='buildings',
            name='accounts_payable_extension',
            field=models.BooleanField(default=False, verbose_name='Accounts Payable Package Extension'),
        ),
        migrations.AddField(
            model_name='buildings',
            name='accounts_receivable_extension',
            field=models.BooleanField(default=False, verbose_name='Accounts Receivable Package Extension'),
        ),
        migrations.AddField(
            model_name='buildings',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='building_address_set', to='contacts.addresses'),
        ),
        migrations.AddField(
            model_name='buildings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildings',
            name='maintenance_extension',
            field=models.BooleanField(default=False, verbose_name='Maintenance Package Extension'),
        ),
        migrations.AddField(
            model_name='buildings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='buildings',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='buildings_company_set', to='companies.companies'),
        ),
    ]
