# Generated by Django 3.2.8 on 2021-11-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralLedgerCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='General Ledger Name')),
                ('code', models.CharField(blank=True, max_length=15, verbose_name='General Ledger Code')),
                ('description', models.CharField(blank=True, max_length=1023)),
                ('notes', models.ManyToManyField(blank=True, to='notes.Notes')),
            ],
            options={
                'verbose_name': 'General Ledger Code',
                'verbose_name_plural': 'General Ledger Codes',
                'ordering': ('name', 'code'),
            },
        ),
    ]
