# Generated by Django 3.2.8 on 2021-11-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        ('general_ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalledgercodes',
            name='notes',
            field=models.ManyToManyField(blank=True, related_name='general_ledger_notes_set', to='notes.Notes'),
        ),
    ]
