# Generated by Django 3.2.8 on 2021-12-01 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='previous_note',
            new_name='changed_to',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='active',
        ),
    ]
